[custom.all.query-based]
type   = "local"
path   = "."
ipkg   = "query-based.ipkg"
test   = "test/test.ipkg"

[custom.all]
ref1.commit                      = "latest:main"
quantifiers-extra.commit         = "latest:main"
