[custom.all.query-based]
type   = "local"
path   = "."
ipkg   = "query-based.ipkg"
test   = "test/test.ipkg"

[custom.all]
ilex-core.commit                 = "latest:main"
ilex.commit                      = "latest:main"
